/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchRoundRoundidIndexRouteImport } from './routes/match/round/$roundid/index'
import { Route as MatchRoundRoundidResultRouteImport } from './routes/match/round/$roundid/result'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoundRoundidIndexRoute = MatchRoundRoundidIndexRouteImport.update({
  id: '/match/round/$roundid/',
  path: '/match/round/$roundid/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoundRoundidResultRoute = MatchRoundRoundidResultRouteImport.update({
  id: '/match/round/$roundid/result',
  path: '/match/round/$roundid/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/match/round/$roundid/result': typeof MatchRoundRoundidResultRoute
  '/match/round/$roundid': typeof MatchRoundRoundidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/match/round/$roundid/result': typeof MatchRoundRoundidResultRoute
  '/match/round/$roundid': typeof MatchRoundRoundidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/match/round/$roundid/result': typeof MatchRoundRoundidResultRoute
  '/match/round/$roundid/': typeof MatchRoundRoundidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/result'
    | '/match/round/$roundid/result'
    | '/match/round/$roundid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result' | '/match/round/$roundid/result' | '/match/round/$roundid'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/match/round/$roundid/result'
    | '/match/round/$roundid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  MatchRoundRoundidResultRoute: typeof MatchRoundRoundidResultRoute
  MatchRoundRoundidIndexRoute: typeof MatchRoundRoundidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/round/$roundid/': {
      id: '/match/round/$roundid/'
      path: '/match/round/$roundid'
      fullPath: '/match/round/$roundid'
      preLoaderRoute: typeof MatchRoundRoundidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/round/$roundid/result': {
      id: '/match/round/$roundid/result'
      path: '/match/round/$roundid/result'
      fullPath: '/match/round/$roundid/result'
      preLoaderRoute: typeof MatchRoundRoundidResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  MatchRoundRoundidResultRoute: MatchRoundRoundidResultRoute,
  MatchRoundRoundidIndexRoute: MatchRoundRoundidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
